version: '3.4'

services:
  php-fpm:
    build:
      context: .
      target: products_php
    volumes:
      - .:/var/www/html
    ports:
      - "8088:8080"

  # nginx:
  #   build:
  #     context: .
  #     target: products_nginx
  #   depends_on:
  #     - php-fpm
  #   ports:
  #     - "83:80"

  mysql:
    image: mariadb:10.6
    container_name: products_mysql
    tty: true
    ports:
      - 3309:3306
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_USER: root
      MYSQL_PASSWORD: dbpass
      MYSQL_ROOT_PASSWORD: rootdbpass
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    ports:
    # To learn about configuring Kafka for access across networks see
    # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
#      - "9092:9092"
        - 9092:9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
#      KAFKA_LISTENERS: PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
